<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>44600148-1d47-4f37-97bc-c19e2383d06f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <PackageReference Include="Quartz" Version="3.18.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.0" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" Version="3.18.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MayNghien.Infrastructures\MayNghien.Infrastructures\MayNghien.Infrastructures.csproj" />
    <ProjectReference Include="..\Todo.Commons\Todo.Commons.csproj" />
    <ProjectReference Include="..\Todo.DTOs\Todo.DTOs.csproj" />
    <ProjectReference Include="..\Todo.Models\Todo.Models.csproj" />
    <ProjectReference Include="..\Todo.Repositories\Todo.Repositories.csproj" />
    <ProjectReference Include="..\Todo.Services\Todo.Services.csproj" />
  </ItemGroup>

</Project>
